export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_SUCCESS = " USER_ORDER_SUCCESS";
export const USER_ORDER_FAIL = "USER_ORDER_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = " ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const DELETE_ORDER_REQUEST = " DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = " DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = " DELETE_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
