export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_ADMIN_PRODUCT_REQUEST = "ALL_ADMIN_PRODUCT_REQUEST";
export const ALL_ADMIN_PRODUCT_SUCCESS = "ALL_ADMIN_PRODUCT_SUCCESS";
export const ALL_ADMIN_PRODUCT_FAIL = "ALL_ADMIN_PRODUCT_FAIL";

export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const LATEST_PRODUCT_REQUEST = "LATEST_PRODUCT_REQUEST";
export const LATEST_PRODUCT_SUCCESS = "LATEST_PRODUCT_SUCCESS";
export const LATEST_PRODUCT_FAIL = "LATEST_PRODUCT_FAIL";

export const FEATURED_PRODUCT_REQUEST = "FEATURED_PRODUCT_REQUEST";
export const FEATURED_PRODUCT_SUCCESS = "FEATURED_PRODUCT_SUCCESS";
export const FEATURED_PRODUCT_FAIL = "FEATURED_PRODUCT_FAIL";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
