export const USER_LOGIN_REQUEST = "LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "REGISTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
