export const USER_REGISTER_REQUEST = "REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const EDIT_MY_PROFILE_REQUEST = " EDIT_MY_PROFILE_REQUEST";
export const EDIT_MY_PROFILE_SUCCESS = "EDIT_MY_PROFILE_SUCCESS";
export const EDIT_MY_PROFILE_FAIL= "EDIT_MY_PROFILE_FAIL";

export const EDIT_MY_PASSWORD_REQUEST = " EDIT_MY_PASSWORD_REQUEST";
export const EDIT_MY_PASSWORD_SUCCESS = "EDIT_MY_PASSWORD_SUCCESS";
export const EDIT_MY_PASSWORD_FAIL= "EDIT_MY_PASSWORD_FAIL";


export const ADMIN_EDIT_PROFILE_REQUEST = "ADMIN_EDIT_PROFILE_REQUEST";
export const ADMIN_EDIT_PROFILE_SUCCESS = "ADMIN_EDIT_PROFILE_SUCCESS";
export const ADMIN_EDIT_PROFILE_FAIL= "ADMIN_EDIT_PROFILE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
